### ISSUE TITLE
Some sort of error when running

### ISSUE THREAD

**Issue by sotiris-bos** [lockedbyte/cryptovenom#12] opened 2020-09-23 14:10 UTC
Option: 18
  File "modules/hash/crypt16unix/menu.py", line 12
    print '''

-=[OPTIONS]=-

   1) Hash Encrypt
   
   2) Hash Brute Force
   
   '''
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('''

-=[OPTIONS]=-

   1) Hash Encrypt
   
   2) Hash Brute Force
   
   ''')?

[*] Continue to main?

**Comment by lockedbyte** [comment] 2020-09-23 14:16
Hi @sotiris-bos .

I just checked the issue.

It should be working now.

Confirm me if it is to close the issue.

**Comment by sotiris-bos** [comment] 2020-09-23 14:19
ption: 18


-=[OPTIONS]=-

   1) Hash Encrypt
   
   2) Hash Brute Force
   

Traceback (most recent call last):
  File "modules/hash/crypt16unix/menu.py", line 14, in <module>
    opt = raw_input('\033[1;34m[=]\033[0m Option: ')
NameError: name 'raw_input' is not defined


[*] Continue to main?

**Comment by lockedbyte** [comment] 2020-09-23 14:28
As I suspected, you are running Cryptovenom from Python 3,x

Cryptovenom was created for running on Python 2.x

I'll be moving it to Python 3.x with the time.

Anyways, you can try to use that specific module replacing "raw_input" with "input".

As I didn't created it for Python 3.x you could get more errors, so I would just recommend you to run it from Python 2.x

**Comment by sotiris-bos** [comment] 2020-09-23 14:29
I am using Python 2.7.18

**Comment by lockedbyte** [comment] 2020-09-23 14:33
Sorry, you might be getting confused.

Python 2.x runs `raw_input` fine, then that error would have not been triggered if running Python 2.x

I'm running that version of python 2 too (2.7.28) and works fine:

```
[=] Option: 18


-=[OPTIONS]=-

   1) Hash Encrypt
   
   2) Hash Brute Force
   
   
[=] Option: 1
[=] Hash/Text: foo
[+] h(x) = xENnBbj/0L406r4slh6wdngI


[*] Continue to main? 
```

Try to use the command `python2` instead of `python` which might be calling python 3 actually.

**Comment by sotiris-bos** [comment] 2020-09-23 14:36
Yeah I am running " sudo python2 cryptovenom.py ".

Anyways, I can use it by changing "raw_input" to "input" so it is OK for now.

Thank you very much!

**Comment by lockedbyte** [comment] 2020-09-23 14:39
Try to add this line to check if you are actually running python 2

`print(__import__('sys').version.split(' ')[0])`

It will print your python version

**Comment by sotiris-bos** [comment] 2020-09-23 14:42
2.7.18

 ▄▄· ▄▄▄   ▄· ▄▌ ▄▄▄·▄▄▄▄▄       ▌ ▐·▄▄▄ . ▐ ▄       • ▌ ▄ ·. 
▐█ ▌▪▀▄ █·▐█▪██▌▐█ ▄█•██  ▪     ▪█·█▌▀▄.▀·•█▌▐█▪     ·██ ▐███▪
██ ▄▄▐▀▀▄ ▐█▌▐█▪ ██▀· ▐█.▪ ▄█▀▄ ▐█▐█•▐▀▀▪▄▐█▐▐▌ ▄█▀▄ ▐█ ▌▐▌▐█·
▐███▌▐█•█▌ ▐█▀·.▐█▪·• ▐█▌·▐█▌.▐▌ ███ ▐█▄▄▌██▐█▌▐█▌.▐▌██ ██▌▐█▌
·▀▀▀ .▀  ▀  ▀ • .▀    ▀▀▀  ▀█▄▀▪. ▀   ▀▀▀ ▀▀ █▪ ▀█▄▀▪▀▀  █▪▀▀▀

Version: 1.0.1        << The Cryptography Swiss Army knife >>
--------------------------------------------------------------------
-[MENU]-
        
    0) Crackssistant (NOT YET)
    1) Symmetric Algorithms
    2) Asymmetric Algorithms
    3) Encoding Algorithms
    4) Classical Algorithms
    5) Hash Algorithms
    6) Mathematical Functions
    7) Algorithm Identifiers (Not YET)
    8) String Manipulation
    9) Randomization Functions
   10) Other
   11) About CryptoVenom
    
   99) Exit
   

[=] Option:

**Comment by lockedbyte** [comment] 2020-09-23 15:37
Well, I know what the problem is.

This script is using actually a bad way to call the other modules because when I programmed it, I created the modules separately, and to finish faster I used this way.

Instead of calling it as a Python module, it is calling it directly again with the python interpreter via os.system()

The script is executing python instead of python2, the users who have python command pointing to python3 instead of python2 will experience this bug

The result of this problem is that you are actually executing the main program with Python2 and the module with Python3.

To check it, if you put the debug line: `print(__import__('sys').version.split(' ')[0])` into the module (`modules/hash/crypt16unix/menu.py`) instead in the main program the output version should be 3.x.

As the problem for you appears to be (temporarily) solved, I'll close this issue and open by myself another one to point this out to be fixed in the future.

Thanks for the report.

**Closed as completed by lockedbyte** 2020-09-23 15:37 UTC
